anisayari/createurstech.fr

- assets/css/styles.scss
- index.md
Fix multi selection choice thanks to @Bl3f
> fix multi selection thx to twitch chat ;)

- _data/creators.yml
Hello Anis, 
J'ai ajouté 2 créateurs à ta liste: Pierre Miniggio et moi-même
> Ajout créateurs Pierre + Sofiyan

- index.md
Specials characters in link don't unformed the html template.
> Correction of html format and of the href implementation 

- _data/creators-short.json
Nouvelles catégories pour les créateurs qui ont des catégories leurs correspondants et dont je connais leur domaine.
> Ajout de certaines catégories

- Gemfile.lock
- README.md
- assets/css/styles.scss
- index.md
petite news, j'ai re-régler le filter. Et je me suis amusée à changer l'UI dans le .SCSS, je le trouve plus beau ^^
je conseille d'y jeter un oeil ^^
bonne continuation avec ce magnifique projet ^^
_(PS: j’espère ne pas trop m'être foiré sur la façon de faire, c'est le premier projet communautaire que je fais ^^" )_
> filter + uidesign

- _data/creators-short.json
add christophe casalegno
cookie conecte
harry jmg
imot3k
adrien linuxtrick
xavki  
V2F
driss AS
processus thief
Hackintux
ioodyme
add category to waked, pierre et neoelectron
> ajout de createurs cybersec, admin et dev

- _data/creators-short.json
Adding the youtubeur/streamer Khaos Farbauti who creating cybersecurity/hacking stuff.
> Adding Khaos Farbauti

- _data/creators-short.json
Ajout de ma chaîne Youtube qui parle de dev_mobile.
> Adding Lilian Suzan

- assets/css/styles.scss
- assets/js/filterAndSearch.js
- assets/js/script.js
- index.md
> correction Issue card fix

- assets/css/styles.scss
- assets/js/script.js
- index.md
@anisayari une fonctionnalité de plus à cocher
> Champs de recherche + carte aléatoire

- _data/creators-short.json
J'ai juste ajouté la catégorie dev_web aux créateurs que je connais. Bisous :x:x:x
> fix categories : added dev_web to some of the creators

- index.md
https://github.com/anisayari/createurstech.fr/issues/51
> Fix youtube subscriber count text color in card

- assets/css/styles.scss
https://github.com/anisayari/createurstech.fr/issues/49
> Fix opacity on card

- _data/creators-short.json
https://www.youtube.com/user/monsieurbidouille
> ajout Mr bidouille en makers

- _data/creators-short.json
https://www.youtube.com/channel/UCzLkeUSipfOtSC9of-Q0yiQ
> ajout GOODWIN makers

- _data/creators-short.json
https://www.youtube.com/channel/UCANjJ55UmYmoXm_SW--psXQ
> Ajout Découvre Bitcoin blockchain

- _data/creators-short.json
https://www.youtube.com/channel/UC0JUkXAVVA4qWH1BQRs5N3A
> Ajout Pause Process actu_tech

- Gemfile.lock
- _data/creators-short.json
Add category and set twitter screen name and twitch channel name.
@anisayari Je ne comprends pas, quand je mets à jour le fichier `_data/creators-short.json`, une fois le serveur lancé, les modifications ne se répercutent pas sur le front, c'est normal ? j'ai certainement oublié quelque chose.
> Add info for Thomas Boileau

- _data/creators-short.json
Hi Anis,
Just added 3 new creators ;)
> 3 new creators added

- _includes/head.html
- _layouts/default.html
- _sass/_base.scss
- _sass/_layout.scss
- _sass/custom-styles.scss
- _sass/custom-variables.scss
- _sass/main.scss
- index.md
C'est surtout un peu de réorganisation de code... il n'y a aucun changement visuel hormis que maintenant le site utilise la font Inter partout comme indiqué sur les maquettes d'où a été tiré le header.
> start of cleaning scss files

- _config.yml
- _includes/header.html
- _sass/_base.scss
- _sass/custom-styles.scss
- _sass/main.scss
- assets/js/filterAndSearch.js
- assets/js/script.js
- index.md
J'ai bien dégrossi le travail sur le style... Je pense avoir plus ou moins fini... je sais pas si je continuerai sur cette branche ou si ça sera fait au fur et à mesure vu ce qui reste...
Maintenant faut voir dans quelle direction on part pour l'intégration... j'aimais bien celle là #68 (avec quelques modifs) mais vous avez pas l'air d'être parti sur ça...
> Clean styles

- _sass/custom-styles.scss
Adding more consistancy in the grid layout reworking the card compone…nt a little bit with a better usage of flexbox
Before
After
> Better card Layout

- _data/creators-short.json
Sorry Anis, my VSCode just keeps reformating the json format in the creators file, but the only change made here is my screen_name, I saw that no Twitch button was displaying on my card :)
> Just fixing twitch_screen_name for Lior Chamla

- _data/creators-short.json
J'ai ajouté plusieurs youtubeurs actu_tech. J'espère que c'est bon
> Ajout de youtubeurs actu_tech

- .idea/createurstech.fr.iml
- _layouts/default.html
- _sass/_base.scss
- _sass/custom-styles.scss
- assets/js/filterAndSearch.js
- assets/js/script.js
- index.md
Filters are part of a form and using form inputs instead of buttons.
The form values are also used as search params.
Styles and JS updated accordingly.
Minors visual changes in order to increase readability and confort.
Old filters:
Update:
> filters are now part of a form and and uses search params

- .idea/createurstech.fr.iml
- _layouts/default.html
- _sass/_base.scss
- _sass/custom-styles.scss
- assets/js/filterAndSearch.js
- assets/js/script.js
- index.md
Reverts anisayari/createurstech.fr#113
> Revert "filters are now part of a form and and uses search params"
